// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeekStart } from "./WeekStart";
import type { WindowGeometry } from "./WindowGeometry";

export type AppConfig = { 
/**
 * `None` until the first-run picker resolves a path. See v0.2 spec §4.4.
 */
vdir_root: string | null, collection_visibility: { [key in string]?: boolean }, week_start: WeekStart, window_geometry: WindowGeometry | null, };
