// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WeekStart } from "./WeekStart";

export type AppConfig = { vdir_root: string, collection_visibility: { [key in string]?: boolean }, week_start: WeekStart, };
