// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionId } from "./CollectionId";
import type { EventTime } from "./EventTime";
import type { RRuleSpec } from "./RRuleSpec";

/**
 * User-supplied data for creating a new event.
 */
export type CreateEventRequest = { collection_id: CollectionId, summary: string, description: string | null, location: string | null, start: EventTime, end: EventTime, rrule: RRuleSpec | null, };
