// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionId } from "./CollectionId";
import type { EventTime } from "./EventTime";
import type { RecurringScope } from "./RecurringScope";

/**
 * User-supplied data for deleting an event.
 */
export type DeleteEventRequest = { uid: string, collection_id: CollectionId, 
/**
 * SHA-256 hex of `raw_ics` as last seen by the frontend. The backend
 * re-hashes the on-disk file before mutating and aborts with
 * `CoreError::Conflict` on mismatch.
 */
expected_raw_hash: string, scope: RecurringScope, 
/**
 * For `ThisInstance` and `ThisAndFuture`, identifies which occurrence.
 * Ignored for `All`. Should equal the occurrence's `RECURRENCE-ID`.
 */
occurrence: EventTime | null, };
