// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionId } from "./CollectionId";
import type { EventTime } from "./EventTime";

/**
 * A single concrete occurrence. Derived on query; never persisted.
 */
export type EventInstance = { event_uid: string, collection_id: CollectionId, summary: string, description: string | null, location: string | null, start: EventTime, end: EventTime, is_override: boolean, };
