// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * All four iCalendar DATE-TIME forms modeled explicitly.
 */
export type EventTime = { "kind": "all_day", date: string, } | { "kind": "floating", datetime: string, } | { "kind": "utc", instant: string, } | { "kind": "zoned", zoned: string, };
