// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventTime } from "./EventTime";

/**
 * A single override of a recurring event (a VEVENT with a `RECURRENCE-ID`).
 */
export type OverrideInstance = { recurrence_id: EventTime, start: EventTime, end: EventTime, summary: string | null, description: string | null, location: string | null, };
