// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which recurring scope a delete or edit applies to. See v0.2 spec §4.3.
 */
export type RecurringScope = "this_instance" | "this_and_future" | "all";
