// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Verbatim `RRULE` line (everything after `RRULE:`).
 */
export type RRuleSpec = { line: string, };
