// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionId } from "./CollectionId";
import type { EventTime } from "./EventTime";
import type { RRuleSpec } from "./RRuleSpec";
import type { RecurringScope } from "./RecurringScope";

/**
 * User-supplied data for editing an event.
 *
 * Carries the full new field set for the event being edited. Semantics
 * depend on `scope`:
 *
 * * `All` — mutate the master VEVENT in place with these values.
 * * `ThisInstance` — append a new override VEVENT pinned to `occurrence`
 *   carrying these values; master is untouched apart from the override.
 * * `ThisAndFuture` — truncate the master `RRULE` with `UNTIL=occurrence`,
 *   drop any overrides at-or-after `occurrence`, and create a *new* file
 *   with a fresh UID carrying these values (the continuation series).
 *   The new UID is returned from `update_event`.
 *
 * See v0.2 spec §4.2 / §4.3 for the design rationale (and the
 * new-UID-on-split decision).
 */
export type UpdateEventRequest = { uid: string, collection_id: CollectionId, expected_raw_hash: string, scope: RecurringScope, occurrence: EventTime | null, summary: string, description: string | null, location: string | null, start: EventTime, end: EventTime, rrule: RRuleSpec | null, };
