// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Window position/size persisted across launches. v0.2 §4.4.
 */
export type WindowGeometry = { width: number, height: number, x: number, y: number, };
