[workspace]
resolver = "2"
members = ["crates/pimple-core", "crates/pimple-tauri"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "GPL-3.0-or-later"
repository = "https://github.com/ryzokuken/pimple"

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"
expect_used = "warn"
panic = "deny"
panic_in_result_fn = "deny"
unimplemented = "deny"
allow_attributes = "deny"
dbg_macro = "deny"
todo = "deny"
print_stdout = "deny"
print_stderr = "deny"
await_holding_lock = "deny"
large_futures = "deny"
exit = "deny"
mem_forget = "deny"
module_name_repetitions = "allow"
similar_names = "allow"

[workspace.dependencies]
jiff = { version = "0.2", features = ["serde", "tzdb-bundle-always"] }
chrono = { version = "0.4", default-features = false, features = ["std", "clock", "serde"] }
chrono-tz = { version = "0.10", default-features = false }
icalendar = { version = "0.17", features = ["parser", "chrono-tz"] }
rrule = { version = "0.14" }
notify = { version = "6", default-features = false, features = ["macos_kqueue"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "fs", "time", "io-util"] }
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ts-rs = { version = "10", features = ["serde-compat"] }
uuid = { version = "1", features = ["v4", "serde"] }
toml = "0.8"
dirs = "5"
