// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionId } from "./CollectionId";

export type Collection = { id: CollectionId, path: string, display_name: string, 
/**
 * CSS hex string, `#RRGGBB`. Read from the `color` file or assigned from the palette.
 */
color: string, 
/**
 * App-local visibility; never written to the vdir.
 */
visible: boolean, };
