// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CollectionId } from "./CollectionId";
import type { EventTime } from "./EventTime";
import type { OverrideInstance } from "./OverrideInstance";
import type { RRuleSpec } from "./RRuleSpec";

/**
 * Persisted event definition. One per iCalendar UID.
 */
export type Event = { uid: string, collection_id: CollectionId, summary: string, description: string | null, location: string | null, start: EventTime, end: EventTime, rrule: RRuleSpec | null, exdates: Array<EventTime>, overrides: Array<OverrideInstance>, created_at: string, modified_at: string, };
